#!/usr/bin/python
# Filename: toMigrate.py for lociNGS
# shird; 5 july 2011

#convert an IMa2 input file to MIGRATE format
import re
import pymongo
import json
import sys
from Bio import SeqIO
from Bio.Alphabet import generic_protein, generic_dna, generic_nucleotide
import pymongo
from pymongo import Connection
import datetime 

now = datetime.datetime.now()

imaList = []
imaFile = open('IMa2_formatted.txt', 'r')
rows = [ line.strip().split(' ') for line in imaFile ]
populations = {}
numberPerLocus = {}
lengthList = []
outputFile = open('Migrate_formatted.txt', 'w')
outputFile.write(str(rows[2][0]))
outputFile.write(" ")
outputFile.write(str(rows[5][0]))
outputFile.write(" file generated by lociNGS on ")
outputFile.write(now.strftime("%B %d, %Y at %H:%M"))
outputFile.write("\n")

for element in rows[3]:
	populations[element] = []
	numberPops = len(rows[3])
	
for i in range(numberPops+1):  #want to access this by a number, not a name
	numberPerLocus[i] = []

for line in rows[6:]:
	if len(line) > 3 :
		lengthList.append(line[numberPops+1])
		for numb, numberPer in numberPerLocus.iteritems():
			numberPerLocus[numb].append(line[numb][0])		
	else:
		for pop in rows[3]:
			if pop in line[0]:
				populations[pop].append(line)

for y in lengthList:
	outputFile.write(y)
	outputFile.write(" ")
outputFile.write("\n")

for i in range(1, numberPops+1):
	for x in numberPerLocus[i]:
		outputFile.write(x)
		outputFile.write(" ")
	outputFile.write(rows[3][i-1])
	outputFile.write("\n")
	for z in populations[rows[3][i-1]]:
		outputFile.write(z[0])
		outputFile.write(" ")
		outputFile.write(z[1])
		outputFile.write("\n")